apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pvc
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/data"
    server: 192.168.1.53