apiVersion: v1
kind: Service
metadata:
  name: ai-image-recognition-service
spec:
  selector:
    app: ai-image-recognition
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
