apiVersion: v1
kind: Service
metadata:
  name: ai-image-recognition-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30143   # You can specify any available port here
  selector:
    app: ai-image-recognition
