apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pvc
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "C:/CloudEngineeringPOCs/AI-ML-Edureka/AIML_POCs/CNN_ImageIDed/data"
    server: 192.168.1.53